"""Create all tables

Revision ID: c6bf776c4d3f
Revises:
Create Date: 2025-08-15 18:04:59.806426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6bf776c4d3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('content_count', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_tags_name'), 'content_tags', ['name'], unique=True)
    op.create_table('content_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('visual_style', sa.JSON(), nullable=True),
    sa.Column('animation_presets', sa.JSON(), nullable=True),
    sa.Column('color_scheme', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('age_groups', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('difficulty_levels', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('asset_urls', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_email'), 'creators', ['email'], unique=True)
    op.create_index(op.f('ix_creators_is_active'), 'creators', ['is_active'], unique=False)
    op.create_index(op.f('ix_creators_username'), 'creators', ['username'], unique=True)
    op.create_table('student_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('preferred_video_duration', sa.Integer(), nullable=True),
    sa.Column('preferred_learning_time', sa.String(length=20), nullable=True),
    sa.Column('preferred_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('avoided_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('auto_play_next', sa.Boolean(), nullable=True),
    sa.Column('show_captions', sa.Boolean(), nullable=True),
    sa.Column('haptic_feedback', sa.Boolean(), nullable=True),
    sa.Column('daily_reminder', sa.Boolean(), nullable=True),
    sa.Column('streak_notifications', sa.Boolean(), nullable=True),
    sa.Column('achievement_notifications', sa.Boolean(), nullable=True),
    sa.Column('learning_tips', sa.Boolean(), nullable=True),
    sa.Column('max_daily_screen_time', sa.Integer(), nullable=True),
    sa.Column('allowed_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('parent_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_preferences_student_id'), 'student_preferences', ['student_id'], unique=False)
    op.create_table('student_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('videos_watched', sa.Integer(), nullable=True),
    sa.Column('quizzes_completed', sa.Integer(), nullable=True),
    sa.Column('quizzes_correct', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('average_video_completion', sa.Integer(), nullable=True),
    sa.Column('average_quiz_response_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_sessions_student_id'), 'student_sessions', ['student_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('age_group', sa.String(length=10), nullable=False),
    sa.Column('learning_preferences', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('accessibility_settings', sa.JSON(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('total_videos_watched', sa.Integer(), nullable=True),
    sa.Column('total_quiz_correct', sa.Integer(), nullable=True),
    sa.Column('total_quiz_attempts', sa.Integer(), nullable=True),
    sa.Column('achievements_unlocked', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('badges_earned', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('completed_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_learning_path', sa.String(length=255), nullable=True),
    sa.Column('preferred_difficulty', sa.Integer(), nullable=True),
    sa.Column('average_session_duration', sa.Integer(), nullable=True),
    sa.Column('last_video_watched', sa.UUID(), nullable=True),
    sa.Column('favorite_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('parent_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('streak_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_age_group'), 'students', ['age_group'], unique=False)
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=True)
    op.create_table('content_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('concept_prompt', sa.Text(), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('subject_area', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('ai_generated_script', sa.Text(), nullable=True),
    sa.Column('visual_storyboard', sa.JSON(), nullable=True),
    sa.Column('voice_config', sa.JSON(), nullable=True),
    sa.Column('music_config', sa.JSON(), nullable=True),
    sa.Column('human_edited_script', sa.Text(), nullable=True),
    sa.Column('visual_modifications', sa.JSON(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('qa_results', sa.JSON(), nullable=True),
    sa.Column('qa_passed', sa.Boolean(), nullable=True),
    sa.Column('manual_review_required', sa.Boolean(), nullable=True),
    sa.Column('generation_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_generation_time', sa.Integer(), nullable=True),
    sa.Column('ai_service_costs', sa.JSON(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_projects_creator_id'), 'content_projects', ['creator_id'], unique=False)
    op.create_index(op.f('ix_content_projects_status'), 'content_projects', ['status'], unique=False)
    op.create_table('creator_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weekly_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('daily_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weekly_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('auto_approve_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('require_approval_above', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('daily_reset_at', sa.DateTime(), nullable=False),
    sa.Column('weekly_reset_at', sa.DateTime(), nullable=False),
    sa.Column('monthly_reset_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_budgets_creator_id'), 'creator_budgets', ['creator_id'], unique=True)
    op.create_table('ai_service_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('service_model', sa.String(length=100), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_tier', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('characters_processed', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('video_duration', sa.Integer(), nullable=True),
    sa.Column('request_parameters', sa.JSON(), nullable=False),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('cache_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['content_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_service_costs_approval_status'), 'ai_service_costs', ['approval_status'], unique=False)
    op.create_index(op.f('ix_ai_service_costs_cost_tier'), 'ai_service_costs', ['cost_tier'], unique=False)
    op.create_index(op.f('ix_ai_service_costs_creator_id'), 'ai_service_costs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_ai_service_costs_project_id'), 'ai_service_costs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_service_costs_service_type'), 'ai_service_costs', ['service_type'], unique=False)
    op.create_table('learning_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('content_project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('concept', sa.String(length=500), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('encoding_format', sa.String(length=10), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('age_groups', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('subject_area', sa.String(length=100), nullable=False),
    sa.Column('curriculum_standards', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('quiz_questions', sa.JSON(), nullable=False),
    sa.Column('quiz_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('average_quiz_score', sa.Float(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('bookmark_count', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('educational_effectiveness', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('generation_config', sa.JSON(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('human_review_notes', sa.Text(), nullable=True),
    sa.Column('qa_results', sa.JSON(), nullable=True),
    sa.Column('factual_accuracy_score', sa.Float(), nullable=True),
    sa.Column('age_appropriateness_score', sa.Float(), nullable=True),
    sa.Column('engagement_prediction', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_project_id'], ['content_projects.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_videos_content_project_id'), 'learning_videos', ['content_project_id'], unique=True)
    op.create_index(op.f('ix_learning_videos_creator_id'), 'learning_videos', ['creator_id'], unique=False)
    op.create_index(op.f('ix_learning_videos_status'), 'learning_videos', ['status'], unique=False)
    op.create_index(op.f('ix_learning_videos_topic'), 'learning_videos', ['topic'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cost_entry_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('operation_description', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cost_tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approval_method', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_entry_id'], ['ai_service_costs.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_cost_entry_id'), 'approval_requests', ['cost_entry_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_creator_id'), 'approval_requests', ['creator_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('explanation', sa.String(length=2000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['learning_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_video_id'), 'quizzes', ['video_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('quiz_id', sa.UUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['learning_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_creator_id'), 'analytics_events', ['creator_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_quiz_id'), 'analytics_events', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_student_id'), 'analytics_events', ['student_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_video_id'), 'analytics_events', ['video_id'], unique=False)
    op.create_table('quiz_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('submitted_answer', sa.String(length=10), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['learning_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_responses_quiz_id'), 'quiz_responses', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_responses_student_id'), 'quiz_responses', ['student_id'], unique=False)
    op.create_index(op.f('ix_quiz_responses_video_id'), 'quiz_responses', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_responses_video_id'), table_name='quiz_responses')
    op.drop_index(op.f('ix_quiz_responses_student_id'), table_name='quiz_responses')
    op.drop_index(op.f('ix_quiz_responses_quiz_id'), table_name='quiz_responses')
    op.drop_table('quiz_responses')
    op.drop_index(op.f('ix_analytics_events_video_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_student_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_quiz_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_creator_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_quizzes_video_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_creator_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_cost_entry_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_learning_videos_topic'), table_name='learning_videos')
    op.drop_index(op.f('ix_learning_videos_status'), table_name='learning_videos')
    op.drop_index(op.f('ix_learning_videos_creator_id'), table_name='learning_videos')
    op.drop_index(op.f('ix_learning_videos_content_project_id'), table_name='learning_videos')
    op.drop_table('learning_videos')
    op.drop_index(op.f('ix_ai_service_costs_service_type'), table_name='ai_service_costs')
    op.drop_index(op.f('ix_ai_service_costs_project_id'), table_name='ai_service_costs')
    op.drop_index(op.f('ix_ai_service_costs_creator_id'), table_name='ai_service_costs')
    op.drop_index(op.f('ix_ai_service_costs_cost_tier'), table_name='ai_service_costs')
    op.drop_index(op.f('ix_ai_service_costs_approval_status'), table_name='ai_service_costs')
    op.drop_table('ai_service_costs')
    op.drop_index(op.f('ix_creator_budgets_creator_id'), table_name='creator_budgets')
    op.drop_table('creator_budgets')
    op.drop_index(op.f('ix_content_projects_status'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_creator_id'), table_name='content_projects')
    op.drop_table('content_projects')
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.drop_index(op.f('ix_students_age_group'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_student_sessions_student_id'), table_name='student_sessions')
    op.drop_table('student_sessions')
    op.drop_index(op.f('ix_student_preferences_student_id'), table_name='student_preferences')
    op.drop_table('student_preferences')
    op.drop_index(op.f('ix_creators_username'), table_name='creators')
    op.drop_index(op.f('ix_creators_is_active'), table_name='creators')
    op.drop_index(op.f('ix_creators_email'), table_name='creators')
    op.drop_table('creators')
    op.drop_table('content_templates')
    op.drop_index(op.f('ix_content_tags_name'), table_name='content_tags')
    op.drop_table('content_tags')
    # ### end Alembic commands ###
